name: flutterfire_gallery
description: A Firebase Flutter Gallery Application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # Firebase Dependencies
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  cloud_firestore: ^0.14.1+3

  # Google Auth
  google_sign_in: ^4.5.5

  # Providers
  provider: ^4.3.2+2

  # Email Validator
  email_validator: ^1.0.6

  # UUID
  uuid: ^2.2.2

  # Image Picker
  image_picker: ^0.6.7+12

  # Download Images
  image_downloader: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
